### ISSUE TITLE
custom dataset to train VAE 

### ISSUE THREAD

**Issue by creatorcao** [CreamyLong/stable-diffusion#15]
Hi, thank you for making this repo available!
Can you tell me how to train a VAE using a custom dataset? 

```
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: True
    train:
      target: ldm.data.imagenet.ImageNetSRTrain
      params:
        size: 256
        degradation: pil_nearest
    validation:
      target: ldm.data.imagenet.ImageNetSRValidation
      params:
        size: 256
        degradation: pil_nearest

```
